sumoheavy/jira-ruby

README.rdoc, lib/jira/oauth_client.rb
Doing this in order to be able to pass Consumer#get_request_token (oauth) some extra parameters (oauth_callback, for instance).
See http://rubydoc.info/gems/oauth/0.4.7/OAuth/Consumer
=> Added extra options to pass to Consumer#get_request_token

lib/jira.rb, lib/jira/client.rb, lib/jira/resource/rapidview.rb, spec/integration/rapidview_spec.rb, spec/mock_responses/rapidview.json, spec/mock_responses/rapidview/SAMPLEPROJECT.issues.full.json, spec/mock_responses/rapidview/SAMPLEPROJECT.issues.json, spec/mock_responses/rapidview/SAMPLEPROJECT.json
Added basic support for JIRA Agile boards.
Usage:
```ruby
client = JIRA::Client.new(options)
boards = client.RapidView.all
board = client.RapidView.find(1)
issues = board.issues
```
Probably will also need to add descriptive error messages when trying to get boards from non-agile JIRA instance.
=> Added basic RapidViews(Agile boards) support

lib/jira/resource/issue.rb, spec/integration/issue_spec.rb, spec/jira/resource/issue_spec.rb
This pull request fixes the bug mentioned in issue #69 where `Issue.all` was passing the wrong arguments to `client.get`. This PR fixes this by constructing the correct URL and adds tests that were missing (or hadn't been updated).
=> Fix bug in Issue.all where client is passed bad arguments

lib/jira/resource/issue.rb, spec/jira/resource/issue_spec.rb
Just a small change to allow specifying expand parameters in a JQL search of issues.
=> Add support for specifying expand in Issue.jql

lib/jira/base.rb
Up until this fix, I was unable to save tickets back to our JIRA environment.  We were ending up with URLs that did not start with a "/".  I've updated the code such that a leading slash is now enforced.  The specs do not break as a result of this fix either.
The configuration we were using is the following (though I've substituted our site with a dummy site name):
```
{
:username => ENV['JIRA_USERNAME'], 
:password => ENV['JIRA_PASSWORD'], 
:site => "https://mycompany.atlassian.net/", 
:context_path => "", 
:auth_type => :basic
}
```
=> Issue #105: Ensuring that URLs begin with a slash "/" character

lib/jira/base.rb
This modification should fix:
jira/base.rb:417:in `+': no implicit conversion of nil into String (TypeError)
=> Added to_s to fix nil implicit converion in base.rb

lib/jira/resource/issue.rb
Added `has_many :fixVersions [...]` to the Issue class, so that `issue.fixVersions` consistently returns versions, just like `issue.versions`.
=> Make issues able to have fix versions

README.rdoc, lib/jira/http_client.rb, spec/jira/http_client_spec.rb
`read_timeout` parameter can be used optionally when there is a large JIRA data set to be extracted.
=> Added http request read timeout

README.rdoc
The Travis CI link was overflowing into the first line of text. My text editor also auto removed some excess white space. Let me know if the white space is intentional.
Additionally, the example code didn't work for me on Rails 4.1.8 since the values in the jira_auth session were in string keys (rather than symbols) and the hash was not an indifferent access hash. I did not change the Sinatra example since I don't know how Sinatra handles its session variables but that example might need to be changed as well.
=> fix README rdoc syntax

README.rdoc
Setting this to "" in the options is required for hosted Atlassian installs.
=> Add a note on hosted Atlassian Jira's context_path.

lib/jira/client.rb, lib/jira/version.rb
This is implemented as a simple 'puts' for now.
Added an option 'http_debug' that can also be set as an option.
Optimally this should be a logger, and with to levels of logging - one for the request, and then a more verbose mode that logs the response.
=> Add an option to print the url for http requests being sent

Gemfile, Guardfile, Rakefile, example.rb, lib/jira/client.rb, lib/jira/resource/field.rb, lib/jira/resource/issue.rb, lib/jira/version.rb, spec/jira/resource/field_spec.rb, spec/jira/resource/issue_spec.rb
These are some changes intended to make dealing with custom fields easier.
Hopefully it fits with your intent for the project.  I think it probably fills the needs of many JIRA users, and I hope I've implemented it in a way that works for you.  I see this being extensible to other areas as well - other settings that are kept at the Jira server level (and so should be associated with the client object), rather than at a level that should be associated with the resource.  
It also includes the http_debug functionality from my earlier pull request (sorry, I should have segmented that out, but it seems very innocuous and useful). It also includes some configuration for the use of guard [you will likely want to exclude change 9ecee2e].  I'm still getting the hang of branching in github for …
=> Custom field handling

lib/jira/resource/user.rb, spec/jira/resource/user_factory_spec.rb
This allows for the retrieval of the currently authenticated user via https://docs.atlassian.com/jira/REST/latest/#api/2/myself-getUser.
=> Implement UserFactory#myself

lib/jira.rb
Fix the inflector to use regex instead of a string. 
I tested this with a rails console and verified that it indeed kept `Status` correctly and allowed `ThingStatuses` to be converted correctly when using `classify`
Fixes: https://github.com/sumoheavy/jira-ruby/issues/148
=> [inflector] fix the active record inflector to support plurals correctly

lib/jira/client.rb, lib/jira/http_client.rb, spec/jira/client_spec.rb
Hi! There are some cases when basic auth doesn't work(https://answers.atlassian.com/questions/203977/jira-api-basic-authentication-not-work). Cookie-based authentication(https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-cookie-based-authentication) works fine in such cases, so I propose to add such authentication to this library.
=> cookie based authentication implemented

lib/jira/resource/issue.rb, spec/jira/resource/issue_spec.rb
Added a use case when Max_Results = 0.
It returns the count of issues and not an array of issues (which should be empty).
People use Max_Results = 0 to only get the count of the issues and not the datas of the issues.
Added one test for it.
=> If max_results set to 0, return count of issues instead of issues

lib/jira/railtie.rb
In f1529f5545e38ad13bc4bc7b809035fcbe8673bb the require was changed from
jira-ruby to jira, but a corresponding change was not made to railtie,
which means that in a Rails application that wishes to use this gem, we
would fail to find the nonexistent file "jira" unless this change is
made (or a file named "jira" happens to be present, but that's an ugly
workaround).
=> railtie: change require to jira-ruby from jira

lib/jira/base.rb
#107: When trying to expand User resource, it fails because url_with_query_params method in JIRA::Base class doesn't take into account that the url parameter passed already has query params.
=> Issue #107: Incorrect query params appended

lib/jira/resource/issue.rb
Such a great gem! Rare case of truly clever implementation. Special thanx for Field.map_fields 👍 
Allows to write code for getting JIRA API data in seconds
Here is my modest contribution - to solve issue of this kind:
```
/rest/api/2/search?jql=%28City_Australia+%3D+Berlin%29+City_Germany+%3D+Berlin
D, [2016-10-13T11:48:58.085781 #5377] DEBUG -- : [httplog] Status: 400
D, [2016-10-13T11:48:58.087346 #5377] DEBUG -- : [httplog] Response:
{"errorMessages":["The option 'Berlin' for field 'City_Australia' does not exist."],"errors":{}}
rake aborted!
JIRA::HTTPError: Bad Request
```
=> validate_query: false for jql

lib/jira/resource/project.rb, spec/jira/resource/project_spec.rb
In order to retrieve more than the 50 first users
REST documentation: https://docs.atlassian.com/jira/REST/cloud/#api/2/user-findAssignableUsers
Please let me know what you may need more in order to have this feature as part of the gem.
=> Paginate JIRA::Resource::Project#users

lib/jira/resource/attachment.rb, spec/jira/resource/attachment_spec.rb
Use `Attachment.meta(client)` to fetch meta info i.e. uploadLimit
=> Issue #223: Add attachment meta

lib/jira/client.rb, lib/jira/http_client.rb, lib/jira/oauth_client.rb, spec/jira/client_spec.rb, spec/jira/http_client_spec.rb
This pull request has two parts to it.  Note, two changes from my previous pull request are also included in this PR.
I have added an `authenticated?` method to the `JIRA::Client` class.  This can be used to check if the user has been authenticated against JIRA.
Also, for cookie authentication I delete the username and password from `client` and `http_client` so that this information does not persist in the application.  This is done as soon as we have received the cookie from JIRA.
For basic authentication, when the client has been created, `authenticated?` will initially return false, since creating the client does not actually involve any calls to the JIRA API.  Once a successful API call has been made `authenticated?` will return true.
I have also added an `authenticated?` to the …
=> Iss 238 cookie improvements

jira-ruby.gemspec
Makes it easy to programatically find the source code and changelog for `jira-ruby`, using the rubygems API. More details on the direction of travel for gemspecs is [here](https://github.com/rubygems/rubygems.org/issues/1127) and [here](https://github.com/rubygems/rubygems.org/pull/1234), and the current state is [here](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb).
(My interest in this is so that [Dependabot](https://dependabot.com) can find a link to the `jira-ruby` source code when it creates PRs. Without that link, we generate PRs like [this one](https://github.com/greysteil/shipment_tracker/pull/36), rather than PRs like [this one](https://github.com/greysteil/shipment_tracker/pull/34).)
=> Add source_code_uri to gemspec

lib/jira/base_factory.rb, lib/jira/resource/agile.rb, spec/jira/resource/agile_spec.rb, spec/mock_responses/board/1_issues.json
You can not receive all issues on a Kanban board with the rapidview REST API call. 
This only works for sprint boards. If you try to access a Kanban board through rapid view API you get an error which says that rapid board requires a project with a backlog.
To get all issues on a Kanban board the board API from agile module could be used. The /issue endpoint returns all known issues. I get all issues with a second call, equal to the implementation in rapidview.rb:+28.
This is my first pull request to a ruby project and my first project with rspec ever. I hope the stuff makes sense. Would be great to have a working gem soon :)
=> Add agile/1.0/board/{boardId}/issue

lib/jira/http_client.rb, spec/jira/http_client_spec.rb
Certain requests, such as those for an issue's `RemoteLink`, would fail because `Net::HTTP` would append the hostname to the full URL path if a proxy were in use. This PR changes this behavior to pass in the request path, since the hostname is already set in the `Net::HTTP.new` call.
Closes #250
=> Make all requests through HttpClient work with proxies

lib/jira/resource/issue.rb, spec/integration/issue_spec.rb, spec/jira/resource/issue_spec.rb, spec/mock_responses/empty_issues.json, spec/mock_responses/issue.json
This should return ALL issues as it says it will.
Keeping count of the size of the result I currently have and then just appending to the array to return.
Setting a max result is optional but I did it anyway.
closes #143
ref: https://github.com/sumoheavy/jira-ruby/pull/174
=> Fix issuea all

README.md, lib/jira/client.rb, lib/jira/oauth_client.rb, spec/jira/client_spec.rb, spec/jira/oauth_client_spec.rb
To support 2 legged oauth for JIRA server only, this is not supported in JIRA cloud, we need to add an `oauth_token` parameter to every request made to the JIRA Rest API.  _See ref A_
I've also added a sample in the ReadMe.
*References*
- Ref a: https://community.atlassian.com/t5/Answers-Developer-Questions/Trying-to-use-Scribe-library-for-2-legged-Oauth-in-JIRA/qaq-p/493695#M31351
=> Add new type of auth in options to support oauth 2legged for server version of JIRA

lib/jira/base.rb
I'm using this gem on a project that's configured to hit a JIRA service that's running on a different machine. The gem works fine to do all read operations—even creating a bug works OK. But for some reason, when calling `save!` or `save`, a leading `/` is added to my URLs. As a result, these requests come back `JIRA::HTTPError: Forbidden`.
=> Removing leading slash from fully qualified URLs

lib/jira/http_error.rb
the message returns nil from jira on HTTPError which in an error response is sort of confusing. I had to go through the source code to find out how response was being stored. This PR stores the body in message so error.message will return the actual message from the server.
=> message to return response body

jira-ruby.gemspec, lib/jira-ruby.rb, lib/jira/client.rb, lib/jira/jwt_client.rb, spec/jira/client_spec.rb
This will add functionality to this gem to make use of JWT authorisation, mainly needed for use with JiraCloud. Example usage:
```
options = {
site: 'http://jiraexample.com',
context_path => '/api/v1.2/jira',
auth_type: : jwt,
: http_debug => true,
: use_ssl => false,
}
client = JIRA :: Client.new (options)
```
=> Add functionality to use JWT authorisation in JiraCloud

lib/jira/client.rb
Add the option to send headers by default in each of the events.
In this way, it is possible to send extra headers to the JIRA server, for example, authentication codes or extra information of the authenticated user.
example:
> 
options = {
: site => 'http://jiraexample.com',
: context_path => '/api/v1.2/jira',
: auth_type =>: cookie,
: use_cookies => true,
: http_debug => true,
: use_ssl => false,
: default_headers => {
"API-KEY" => "HGDFSYE76G5D9",
"CLIENT-EMAIL" => "luis.rangel@corp.com",
"CLIENT-OFFICE => "Cloud devs"
}
}
client = JIRA :: Client.new (options)
=> Add default headers

README.md
Update readme to show basic auth configuration with the now required api token. fixes #280
=> Update readme for basic_auth for api_token

lib/jira/resource/board.rb, spec/jira/resource/board_spec.rb
When getting the issues from a board, remove the superfluous question mark from the query string.
See #304
=> Remove superfluous question mark.

lib/jira/jwt_client.rb, spec/jira/jwt_uri_builder_spec.rb
Parsing of the url was not done correctly, resulting in two `?` signs in the url and the JWT token to not be recognised.
=> Fix a bug with multiple params for JTW clients

jira-ruby.gemspec
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement.
=> gemspec: drop rubyforge_project, it is EOL

.travis.yml
As Ruby 2.3 support has been finished in 2019-03, it might be optionally considered to remove 2.3 😄
=> Ensure Ruby 2.5/2.6-based tests on CI process

.travis.yml
Support of Ruby 2.3 has ended
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/
=> Drop CI for ruby 2.3

lib/jira/http_client.rb, spec/jira/http_client_spec.rb
In my quest to get [OAuth 2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-authorization-code-grants-3lo-for-apps/) functionality working by configuring the basic `HttpClient` I encountered some unexpected behaviour.
```ruby
JIRA::Client.new(
auth_type: :basic,
site: 'https://api.atlassian.com/ex/jira',
context_path: "/ex/jira/#{integration.account_id}",
default_headers: {
'Authorization' => "Bearer #{integration.token}"
}
)
```
I assumed that if I didn't pass a `username`/`password`, it would not set the basic auth header in the request. Instead I had to explicitly set the `username`/`password` to `nil`.
The other option would be to leave the defaults as empty strings but change the check to something like `!@options[:username].to_s.empty?`
=> Default HttpClient basic auth credentials to nil

lib/jira/client.rb, lib/jira/http_client.rb, spec/jira/http_client_spec.rb
Adds the necessary code to allow callers to specify a fixed SSL Version for the HTTP
connections.
Addresses: #307
=> Add the :ssl_version option to the JIRA::Client class

lib/jira/client.rb
method Sprint was duplicated in lib/jira/client.rb
=> Remove duplicate method definition in client.rb

lib/jira/client.rb, lib/jira/http_client.rb, spec/jira/http_client_spec.rb
`jira-ruby` didn't support proxies that require authentication, though `Net::HTTP::Proxy` does.  This adds an option to use such proxies.
=> Add support for proxy usernames/passwords

lib/jira-ruby.rb, lib/jira/client.rb, lib/jira/resource/board.rb, lib/jira/resource/board_configuration.rb, spec/jira/resource/board_spec.rb
Why?
Allow for lookup of configuration information for a specific board.
See JIRA API documentation:
https://developer.atlassian.com/cloud/jira/software/rest/#api-rest-agile-1-0-board-boardId-configuration-get
Completes #316
=> Add BoardConfiguration API

lib/jira/resource/attachment.rb, spec/jira/resource/attachment_spec.rb
When calling `save` on an attachment, the base class calls the `save!` method with two parameters (attrs, path), causing it to fail with `wrong number of arguments`.
This fixes #314.
=> Fix save method not working on attachments

lib/jira/resource/watcher.rb, spec/integration/watcher_spec.rb
When adding a watcher to a Jira issue, the API request succeeds but jira-ruby throws the following NoMethodError:
`undefined method 'each' for "kevin":String`
immediately afterwards when trying to parse and set attributes from the request body.
The reason for this bug is because the [Jira API endpoint for adding a watcher to an issue requires a regular string for the request body, rather than hash](https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-issue-issueIdOrKey-watchers-post) (with a string being a user id, like "kevin"), whereas most other endpoints require a hash. The default save! method in `base.rb` attempts to parse and set key-value attributes from the request body, but iteration (each) can't be done over a regular string like with a hash.
In this PR I …
=> Fixed support for adding watchers to issues

lib/jira/resource/attachment.rb, spec/jira/resource/attachment_spec.rb
When uploading image attachments to JIRA with the current `application/binary` forced mimeType, image previews does not work. The thumbnail is generated and shown properly, but clicking the file opens a dialog saying: "Ouch! We can't preview this file type."
Setting the correct mimeType for the image makes the preview dialog work.
I used symbols for hash keys instead of strings to standardize with the other examples. There's a check to make sure that the old `'file'` argument as string is still supported for backwards compatibility.
=> Add mimeType parameter to make JIRA image preview work

lib/jira/client.rb, lib/jira/http_client.rb, lib/jira/http_error.rb, lib/jira/jwt_client.rb, lib/jira/oauth_client.rb, lib/jira/request_client.rb, lib/jira/resource/attachment.rb, spec/jira/http_client_spec.rb, spec/jira/oauth_client_spec.rb, spec/jira/request_client_spec.rb, spec/jira/resource/attachment_spec.rb
The current implementation of attachments only works when using the `basic_auth` client types.
This PR will add functionality so attachments can be used by all client types available.
Next to that some of the specs are refactored a bit.
=> Add multipart attachments for all client types

.travis.yml
ruby-head is currently at `2.8.0dev` when 2.7 has just been released, I think we should explicit the versions we want to test.
=> Set explicit ruby versions for travis

.gitignore, lib/jira/resource/sprint.rb, spec/jira/resource/sprint_spec.rb
Original code ignored client#options[:context_path].  This addresses the issue.  Have also added an RSpec to test that the URL is correctly formed.  All tests pass.
I use RubyMine which has automatically created a .rakeTasks - have added to the .gitignore.  Feel free to remove from the pull request.
=> Fixes Sprint::find to use context_path correctly

lib/jira/client.rb, spec/jira/client_spec.rb
When creating an instance of a JIRA::CLient, raise ArgumentError if the
option is unknown.
Fixes sumoheavy/jira-ruby#356
=> Throw exception when passing unknown option.

lib/jira/client.rb
It is used in http_client, and the example in README uses it.
=> Add read_timeout to accepted options

lib/jira/client.rb
The `DEFINED_OPTIONS` constant is missing `cert_path` and `key_path` making impossible to verify client's ssl files.
=> Add_Cert_and_key_options

lib/jira/client.rb, lib/jira/http_client.rb, spec/jira/client_spec.rb, spec/jira/http_client_spec.rb
Currently ssl client certificate and key file paths are only supported for verification, this change provides the ability to pass down the cert and key as strings instead of reading from disk using the `ssl_client_cert` and `ssl_client_key` options.
File paths will override the strings in case they are provided too, also renaming `cert` and `key` options to have a more meaningful name.
=> Adding support for ssl client certificate and key text based

lib/jira/client.rb
this is typically used in the printing of the object to console or log.  All tests ran and passed.  This resolves #266
=> This change will only effect object inspections

lib/jira/client.rb
After 731ecd8, we throw an exception when passing an unknown option. I think we are missing `use_cookies`.
At the moment, the example [Configuring JIRA to use Cookie-Based Auth](https://github.com/sumoheavy/jira-ruby#configuring-jira-to-use-cookie-based-auth) from the README fails:
```ruby
$ pry
[1] pry(main)> require 'jira-ruby'
=> true
[2] pry(main)>
[3] pry(main)> options = {
[3] pry(main)*   :username           => 'username',
[3] pry(main)*   :password           => 'pass1234',
[3] pry(main)*   :site               => 'http://mydomain.atlassian.net:443/',
[3] pry(main)*   :context_path       => '',
[3] pry(main)*   :auth_type          => :cookie,  # Set cookie based authentication
[3] pry(main)*   :use_cookies        => true,     # Send cookies with each request
[3] pry(main)* …
```
=> Add use_cookies to the available options list

README.md
Related: https://github.com/sumoheavy/jira-ruby/pull/336
=> Fix README example on how to use API token obtained via Jira Cloud account settings

lib/jira/oauth_client.rb, spec/jira/oauth_client_spec.rb
I've noticed a subtle bug: the `&block` received by the `request_token` method was passed into `get_request_token` not as a block reference, which should have been `&block`, but as a mere `block` argument. 
Given the `OAuth::Consumer.get_request_token(request_options = {}, *arguments, &block)` calling contract, the passed `block` was arriving into the `*arguments` array, instead of being bound as the method's block, so the passed block was never been called.
I've added a test for ensuring the block is correctly being processed.
=> Fix JIRA::OauthClient.request_token block passing to get_request_token

lib/jira/client.rb, lib/jira/http_client.rb, spec/jira/http_client_spec.rb
I'm working in an environment where we have our own certificate
authority, and I need to pass a CA file. It doesn't look like there's
currently a way to do so.
I see a similar patch was submitted in
https://github.com/sumoheavy/jira-ruby/pull/279 and it was just
withdrawn because the submitter didn't need it anymore. Now that I'm
seeing a need, I wonder whether there is a possibility of adding it.
I see a monkey-patch solution being offered in
https://github.com/sumoheavy/jira-ruby/issues/140#issuecomment-196534011
but my colleagues are leery of monkey-patching.
I also see from my searches that perhaps setting the environment
variable SSL_CERT_FILE may be able to achieve this, but we're also a
little leery of an implicit reliance on the environment variable, and
think it's better to be …
=> HttpClient: Allow specifying ca_file

.github/workflows/CI.yml, .travis.yml, README.md
- Replaced Travis CI for Github Actions CI
- Updated README
In order to continue doing maintenance and also verify the consistency of the gem, having a CI which is working properly with the newer Ruby versions is a good step ahead 👍🙂
I didn't add `Ruby 3.2` to the CI since it is throwing some errors while running the specs, I'll take a look at it when I have some time, but I just wanted to comment it in case that someone want to contribute there.
https://github.com/sumoheavy/jira-ruby/issues/408
=> Add GitHub actions with newer ruby versions

lib/jira/client.rb, lib/jira/resource/attachment.rb, spec/data/files/short.txt, spec/jira/resource/attachment_spec.rb
I could not upload attachments onto issues.  I got a response that I did not have permissions to view the issue.
However, I found it was a bug that mulitpart posts were not passing the default headers from the client.
I am using OAuth 2.0, passing the Jira OAuth Access Token as a bearer token header.
This PR:
1. Fixes passing default headers with multipart posts.
2. Replaces the deprecated alias UploadIO with Multipart::Post::UploadIO.
=> Multipart default headers

lib/jira/resource/sprint.rb, spec/jira/resource/sprint_spec.rb
Addition of method for adding multiple issues.
Wrote test for [PR 390](https://github.com/sumoheavy/jira-ruby/pull/390/files).
@SimonMiaou This replaces PR 390 as an alternative allowing PR 390 to be closed.
=> Allow adding multiple issues

spec/jira/base_spec.rb, spec/support/shared_examples/integration.rb
When running rspec, there are deprecation warnings which this PR fixes.
=> Change expect for raising to block from advice of deprecation warning.

jira-ruby.gemspec
OAuth 0.6 goes EOL around April 2024. Move to 1.x.
From the bundler output when you install the current version of this gem you get:
> You have installed oauth version 0.6.2, congratulations!
> 
> Non-commercial support for the 0.6.x series will end by April, 2024.
> Please upgrade to 1.0.x as soon as possible! The only breaking change
> will be dropped support for Ruby 2.4, 2.5, and 2.6.
=> chore(gems): Upgrade to OAuth 1.x

lib/jira/resource/attachment.rb, spec/jira/resource/attachment_spec.rb
Adds methods to attachments to download the attachment contents.
=> Attachment download contents

lib/jira/http_error.rb
If `active_support/core_ext/object` was not already loaded and there is an http error, the following undefined method error would be raised:
```
/home/xxxx/.rvm/gems/ruby-3.2.2/gems/jira-ruby-2.3.0/lib/jira/http_error.rb:11:in `initialize': undefined method `presence' for "Bad Request":String (NoMethodError)
@message = response.try(:message).presence || response.try(:body)
^^^^^^^^^
```
The `presence` method is defined by Active Support's Object extensions.
To reproduce this issue, in the root of the project repository, save the following code to a file (say `test.rb`):
```ruby
require 'jira-ruby'
response = Struct.new(:message, :body).new('my message', 'my body')
JIRA::HTTPError.new(response)
```
and then run with the following command run in the repository's root folder:
```shell
ruby …
```
=> Load Active Support's Object extensions

.github/workflows/CI.yml, spec/jira/base_spec.rb
This is an update to the tests to support the change in https://github.com/sumoheavy/jira-ruby/pull/435/files. Introducing `active_support/core_ext/object` changes the behavior of `to_json` so we need to account for that.
=> Update tests for to_json

.github/workflows/CI.yml, Gemfile, jira-ruby.gemspec
The goal of this PR is to prepare some of the backward incompatible changes for the upcoming 3.0.0 release of the gem. It's honestly been a while since we've updated it, but I'm in a position where I can put more time into this. Thank you so much to everyone who continues to contribute and have been using the gem for all this time.
There are a few main things that this covers, which include updates to supported versions of Ruby, updates to the Gemfile, and dependency updates.
- Run tests on both `push` and `pull_request`: This will help preview tests in our PRs
- Dropping support for Ruby <= 3.0: It's going to be harder to support as dependencies and standards improve around the gem, and we don't want to hit a wall where updating would be incredibly difficult or require a complete rewrite …
=> Initial preparations for v3.0.0

README.md
We are no longer using Slack, so I'm removing the link. Other documentation improvements coming shortly.
=> #433 Remove link to deprecated Slack

jira-ruby.gemspec, spec/jira/client_spec.rb, spec/support/clients_helper.rb
The goal of this pull request is to upgrade to webmock 3.x. There are a few changes necessary to accomplish this:
* Update webmock
* Update how we implement authenticated calls
The number of tests reported will drop, due to what I can tell are duplicates running in v1. Looking at the examples below, you'll see that webmock v1.x was running the shared tests twice. This has been remedied.
```
JIRA::Resource::Comment
it should behave like a resource
gracefully handles non-json responses
it should behave like a resource with a collection GET endpoint
should get the collection
it should behave like a resource with a singular GET endpoint
GETs a single resource
builds and fetches a single resource
handles a 404
it should behave like a resource with a DELETE endpoint
deletes a resource
it should …
```
=> #430 Upgrade webmock and tests

README.md
Hello, it took me a long time to figure out authorization via PAT. As a result, it turned out that the documentation contains an outdated usage example, although the information in the paragraph in front of it is valid.
I found that this is a known issue, so the PR probably closes #424
=> Fix personal access token usage example

.rubocop.yml, lib/jira/client.rb, lib/jira/resource/field.rb, spec/integration/user_spec.rb, spec/jira/resource/board_spec.rb, spec/jira/resource/field_spec.rb, spec/jira/resource/issue_spec.rb, spec/jira/resource/status_spec.rb
Loading the gem on Ruby 3.3.5 or 3.4.0-preview1 prints this warning:
lib/jira-ruby.rb:53: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
OpenStruct is used to store two values (`field_map` and `field_map_reverse`) but only `field_map` was actually used, so we can store it directly in an instance variable and remove the dependency on OpenStruct.
=> Remove OpenStruct usage
