lib/jira/base.rb, lib/jira/resource/issue.rb, spec/jira/base_spec.rb, spec/jira/resource/issue_spec.rb
When using Delegator, it's trying to pass a boolean as a 2nd param
=> respond_to? -- wrong number of arguments calling  (2 for 1)

README.rdoc
I noticed that the Sinatra example code wasn't quite working.  This PR updates the Sinatra example code in the README.
=> Update Sinatra Example Code

lib/jira.rb, lib/jira/client.rb, lib/jira/resource/webhook.rb, spec/integration/webhook.rb, spec/mock_responses/jira/rest/webhooks/1.0/webhook.json, spec/mock_responses/jira/rest/webhooks/1.0/webhook/2.json, spec/mock_responses/webhook.json, spec/mock_responses/webhook/webhook.json
Follows the same usage as other resources and includes tests
=> Add Webhook to jira-ruby

lib/jira/base.rb, spec/jira/base_spec.rb
This should resolve https://github.com/sumoheavy/jira-ruby/issues/134
=> allow to_json to accept options hash

lib/jira/client.rb
All-in-the-title.
If this small change can save time for other ...
=> Raise error when :auth_type option is bad.

lib/jira/client.rb, lib/jira/resource/issuecount.rb, spec/jira/resource/issuecount_spec.rb
Hello,
I'm using your gem but I didn't found a way to only get the number of issues without getting all the content.
The REST API has always the field "Total" filled when doing a query so I thought I could make an other class to only return this number.
I'm new to Ruby so maybe I didn't do it the best way.
Tell me if this is a good idea or not :)
Simon
=> IssueCount

Gemfile, jira-ruby.gemspec
https://github.com/sumoheavy/jira-ruby/issues/152
=> Gemspec updates - Issue 152 resolution

lib/jira/base.rb, lib/jira/resource/createmeta.rb, spec/jira/resource/createmeta_spec.rb
Please let me know what you may need in order to have this PR merged
=> Fix JIRA::Resource::Createmeta.all to return valid objects

lib/jira/resource/issue.rb
#151: If issue has more worklogs than 20 than not all worklogs are fetched, this patch solves this problem.
Signed-off-by: Lukasz Gromanowski lgromanowski@gmail.com
=> Issue #151: Fetch all worklogs for given issue

lib/jira/base_factory.rb, lib/jira/resource/agile.rb, spec/jira/resource/agile_spec.rb
Implements: https://docs.atlassian.com/jira-software/REST/cloud/#agile/1.0/board/{boardId}/project
=> Added Agile project and project full

lib/jira/http_client.rb, spec/jira/http_client_spec.rb
Fixes #227 and adds a regression test.
=> Include context_path in make_cookie_auth_request (fixes #227)

lib/jira/base.rb, lib/jira/http_client.rb, spec/jira/http_client_spec.rb, spec/jira/resource/agile_spec.rb
- I reopen the issue #227 as I revert the fix
- I also revert the fact that we raise catch exceptions, it was not making sense the way it was develop. I'd like to introduce better exception in a future version
=> Revert some changes in order to greenify master

lib/jira/http_client.rb, spec/jira/client_spec.rb, spec/jira/http_client_spec.rb
As per my comment on Issue 233 today, PR that applies PR 228 and fixes a minor issue in the RSpec so that all tests pass.
=> Re-applies PR 228, and fixes the RSpec tests to all green.

example.rb
I found `example.rb` rather hard to read for creating an issue. I added some more details, making it more legible, and adding an example for labels, which were rather unclear as well.
Note: I created a separate `labels` variable, because I have been entirely unable to create a ticket by defining it inline, while it always works when I just reference the variable.
=> Adding more details to example code

lib/jira/resource/issue.rb
This should return ALL issues as it says it will.
Keeping count of the size of the result I currently have and then just appending to the array to return.
Setting a max result is optional but I did it anyway.
closes #143
=> fix issues.all

README.md, lib/jira/base.rb, spec/jira/base_spec.rb
=>  Make client tolerate trailing slashes in site option (Fixes #80)

lib/jira/resource/user.rb, spec/integration/user_spec.rb
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-users/#api-rest-api-2-users-search-get
typo? 🤔
=> Fix user all endpoint

lib/jira-ruby.rb
=> Fix loading with active_support 7

README.md
Added example to show how to get PAT to work, address issue https://github.com/sumoheavy/jira-ruby/issues/387
=> added example on how to get Personal Access Token authentication to work

spec/jira/oauth_client_spec.rb, spec/jira/resource/issue_picker_suggestions_spec.rb, spec/jira/resource/issue_spec.rb
This change updates the specs to work with Ruby 3.
=> Update specs to work with Ruby 3

lib/jira/http_client.rb, spec/jira/http_client_spec.rb
Net::HTTP::Proxy was deprecated.
=> Replace obsolete Net::HTTP::Proxy

README.md
Documentation: Enhanced Usage Examples
1.	Revised explanation on how fields can be referred by custom names, emphasizing the unique PascalCase-snake_case mixed naming convention used after mapping.
2.	Added examples to demonstrate usage of the JIRA-Ruby gem, such as connecting to a JIRA instance, retrieving and displaying project details, handling fields by names, performing JQL queries, and executing various actions on the ﻿Issue object.
3.	Elaborated on the additional capabilities of the API wrapper like searching for a user, managing issue links, etc., urging users to refer to the complete script for a comprehensive idea of the gem's functionality.
=> Update README.md to include useage examples in the example.rb file

lib/jira/version.rb
Bumping to 3.0.0 to prepare for the next release
=> Bump version to prepare for the next release
